# =========================
# AI Bash Assistant
# =========================
#
# DESCRIPTION
#   Interactive shell mode powered by Ollama that translates natural language
#   into Bash commands, with optional explanation and execution.
#
# USAGE
#   ai
#
# INTERACTIVE COMMANDS
#   exit, quit     Exit AI mode
#   help           Show this help message
#
# WORKFLOW
#   1. Type a natural language request
#      Example: list all files in ~/tmp
#
#   2. The assistant suggests a Bash command
#
#   3. Choose an action:
#      r   Run the command
#      e   Explain the command
#      s   Skip
#      q   Quit
#
# FEATURES
#   - Arrow keys (↑ ↓) to navigate prompt history
#   - Interactive confirmation before execution
#   - Automatic Ollama startup if not running
#   - Clean command extraction (no markdown)
#
# MODEL CONFIGURATION
#   Default model:
#     qwen2.5-coder:7b
#
#   Override with:
#     export AI_MODEL=your_model_name
#
#   Example:
#     export AI_MODEL=llama3
#
# DEPENDENCIES
#   - ollama must be installed and available in PATH
#
# EXAMPLES
#   ai
#   ai> find all .log files
#   ai> show disk usage
#   ai> count lines in all python files
#
# WARNING
#   Commands are generated by AI and may be unsafe.
#   Always review before executing.
#
# =========================

ai_ensure_ollama() {
  if ! command -v ollama >/dev/null 2>&1; then
    printf 'Error: ollama not found in PATH\n' >&2
    return 1
  fi

  if ! ollama list >/dev/null 2>&1; then
    printf 'Starting ollama service...\n'
    nohup ollama serve >/dev/null 2>&1 &

    local retries=15
    while ! ollama list >/dev/null 2>&1; do
      sleep 1
      retries=$((retries - 1))
      if [ "$retries" -le 0 ]; then
        printf 'Error: ollama service did not start in time\n' >&2
        return 1
      fi
    done
  fi
}

ai_generate_command() {
  local model="$1"
  local user_prompt="$2"

  local system_prompt="You are a Linux expert.
Always return only valid bash commands.
Do not include explanations.
Return commands as plain text.
Do NOT use markdown.
Do NOT use triple backticks.
Do NOT wrap output in code blocks."

  ollama run "$model" "$system_prompt $user_prompt"
}

ai_clean_command() {
  printf '%s' "$1" \
    | sed 's/```bash//g; s/```//g' \
    | tr '\n' ' ' \
    | sed 's/[[:space:]]\+/ /g; s/^ *//; s/ *$//'
}

ai_explain_command() {
  local model="$1"
  local cmd="$2"

  local explain_prompt="You are a Linux expert.
Explain this bash command briefly.
Be concise.
Use plain text."

  ollama run "$model" "$explain_prompt $cmd"
}

ai() {
  local model="${AI_MODEL:-qwen2.5-coder:7b}"
  local prompt raw_cmd cmd answer

  local GREEN=$'\e[32m'
  local CYAN=$'\e[36m'
  local YELLOW=$'\e[33m'
  local RED=$'\e[31m'
  local RESET=$'\e[0m'

  if ! ai_ensure_ollama; then
    printf '%sUnable to start or reach ollama.%s\n' "$RED" "$RESET"
    return 1
  fi

  printf '%sAI mode enabled%s (model: %s%s%s)\n' "$CYAN" "$RESET" "$YELLOW" "$model" "$RESET"
  printf 'Type %sexit%s to quit.\n\n' "$GREEN" "$RESET"

  while true; do
    read -e -r -p "$(printf '%sai>%s ' "$GREEN" "$RESET")" prompt

    case "$prompt" in
      exit|quit)
        printf '%sLeaving AI mode.%s\n' "$CYAN" "$RESET"
        break
        ;;
      "")
        continue
        ;;
    esac

    history -s "$prompt"

    raw_cmd="$(ai_generate_command "$model" "$prompt" 2>/dev/null)"
    cmd="$(ai_clean_command "$raw_cmd")"

    if [ -z "$cmd" ]; then
      printf '%sNo command generated.%s\n\n' "$RED" "$RESET"
      continue
    fi

    printf '\n%sSuggested:%s\n' "$CYAN" "$RESET"
    printf '  %s%s%s\n\n' "$YELLOW" "$cmd" "$RESET"

    printf '[%sr%s]un, [%se%s]xplain, [s]kip, [q]uit: ' "$GREEN" "$RESET" "$CYAN" "$RESET"
    read -r answer

    case "$answer" in
      r|R)
        printf '%sRunning...%s\n' "$GREEN" "$RESET"
        bash -c "$cmd"
        printf '\n'
        ;;
      e|E)
        printf '\n'
        ai_explain_command "$model" "$cmd"
        printf '\n'
        printf 'Run it now? [%sy%s/N] ' "$GREEN" "$RESET"
        read -r answer
        if [[ "$answer" =~ ^[Yy]$ ]]; then
          printf '%sRunning...%s\n' "$GREEN" "$RESET"
          bash -c "$cmd"
          printf '\n'
        else
          printf '%sSkipped.%s\n\n' "$YELLOW" "$RESET"
        fi
        ;;
      q|Q)
        printf '%sLeaving AI mode.%s\n' "$CYAN" "$RESET"
        break
        ;;
      *)
        printf '%sSkipped.%s\n\n' "$YELLOW" "$RESET"
        ;;
    esac
  done
}

