# =========================
# AI Bash Assistant
# =========================
#
# DESCRIPTION
#   Interactive shell mode powered by Ollama that translates natural language
#   into Bash commands, with optional explanation and execution.
#
# USAGE
#   ai
#
# INTERACTIVE COMMANDS
#   exit, quit     Exit AI mode
#   help           Show this help message
#
# WORKFLOW
#   1. Type a natural language request
#      Example: list all files in ~/tmp
#
#   2. The assistant suggests a Bash command
#
#   3. Choose an action:
#      r   Run the command
#      e   Explain the command
#      s   Skip
#      q   Quit
#
# FEATURES
#   - Arrow keys (↑ ↓) to navigate prompt history
#   - Interactive confirmation before execution
#   - Automatic Ollama startup if not running
#   - Clean command extraction (no markdown)
#
# MODEL CONFIGURATION
#   Default model:
#     qwen2.5-coder:7b
#
#   Override with:
#     export AI_MODEL=your_model_name
#
#   Example:
#     export AI_MODEL=llama3
#
# DEPENDENCIES
#   - ollama must be installed and available in PATH
#
# EXAMPLES
#   ai
#   ai> find all .log files
#   ai> show disk usage
#   ai> count lines in all python files
#
# WARNING
#   Commands are generated by AI and may be unsafe.
#   Always review before executing.
#
# =========================

ai_ensure_ollama() {
  if ! command -v ollama >/dev/null 2>&1; then
    printf 'Error: ollama not found in PATH\n' >&2
    return 1
  fi

  if ! ollama list >/dev/null 2>&1; then
    printf 'Starting ollama service...\n'
    nohup ollama serve >/dev/null 2>&1 &

    local retries=15
    while ! ollama list >/dev/null 2>&1; do
      sleep 1
      retries=$((retries - 1))
      if [ "$retries" -le 0 ]; then
        printf 'Error: ollama service did not start in time\n' >&2
        return 1
      fi
    done
  fi
}

ai_generate_command() {
  local model="$1"
  local user_prompt="$2"

  local system_prompt="You are a Linux expert.
Always return only valid bash commands.
Do not include explanations.
Return commands as plain text.
Do NOT use markdown.
Do NOT use triple backticks.
Do NOT wrap output in code blocks."

  ollama run "$model" "$system_prompt $user_prompt"
}

ai_clean_command() {
  printf '%s' "$1" \
    | sed 's/```bash//g; s/```//g' \
    | tr '\n' ' ' \
    | sed 's/[[:space:]]\+/ /g; s/^ *//; s/ *$//'
}

ai_explain_command() {
  local model="$1"
  local cmd="$2"

  local explain_prompt="You are a Linux expert.
Explain this bash command briefly.
Be concise.
Use plain text."

  ollama run "$model" "$explain_prompt $cmd"
}

ai() {
  local model="${AI_MODEL:-qwen2.5-coder:7b}"
  local prompt raw_cmd cmd answer

  local GREEN=$'\e[32m'
  local CYAN=$'\e[36m'
  local YELLOW=$'\e[33m'
  local RED=$'\e[31m'
  local RESET=$'\e[0m'

  if ! ai_ensure_ollama; then
    printf '%sUnable to start or reach ollama.%s\n' "$RED" "$RESET"
    return 1
  fi

  printf '%sAI mode enabled%s (model: %s%s%s)\n' "$CYAN" "$RESET" "$YELLOW" "$model" "$RESET"
  printf 'Type %sexit%s to quit.\n\n' "$GREEN" "$RESET"

  while true; do
    read -e -r -p "$(printf '%sai>%s ' "$GREEN" "$RESET")" prompt

    case "$prompt" in
      exit|quit)
        printf '%sLeaving AI mode.%s\n' "$CYAN" "$RESET"
        break
        ;;
      "")
        continue
        ;;
    esac

    history -s "$prompt"

    raw_cmd="$(ai_generate_command "$model" "$prompt" 2>/dev/null)"
    cmd="$(ai_clean_command "$raw_cmd")"

    if [ -z "$cmd" ]; then
      printf '%sNo command generated.%s\n\n' "$RED" "$RESET"
      continue
    fi

    printf '\n%sSuggested:%s\n' "$CYAN" "$RESET"
    printf '  %s%s%s\n\n' "$YELLOW" "$cmd" "$RESET"

    printf '[%sr%s]un, [%se%s]xplain, [s]kip, [q]uit: ' "$GREEN" "$RESET" "$CYAN" "$RESET"
    read -r answer

    case "$answer" in
      r|R)
        printf '%sRunning...%s\n' "$GREEN" "$RESET"
        bash -c "$cmd"
        printf '\n'
        ;;
      e|E)
        printf '\n'
        ai_explain_command "$model" "$cmd"
        printf '\n'
        printf 'Run it now? [%sy%s/N] ' "$GREEN" "$RESET"
        read -r answer
        if [[ "$answer" =~ ^[Yy]$ ]]; then
          printf '%sRunning...%s\n' "$GREEN" "$RESET"
          bash -c "$cmd"
          printf '\n'
        else
          printf '%sSkipped.%s\n\n' "$YELLOW" "$RESET"
        fi
        ;;
      q|Q)
        printf '%sLeaving AI mode.%s\n' "$CYAN" "$RESET"
        break
        ;;
      *)
        printf '%sSkipped.%s\n\n' "$YELLOW" "$RESET"
        ;;
    esac
  done
}

# ===========================

gemini() {
  local histfile="/tmp/gemini_history.txt"
  : > "$histfile"

  trap 'printf "\n\e[31mGame Over 💀\e[0m\n"; return 130' INT

  if [ -z "$GEMINI_API_KEY" ]; then
    printf '\e[31mERROR:\e[0m GEMINI_API_KEY is not set.\n'
    printf 'Run:\n  export GEMINI_API_KEY="your_key_here"\n'
    return 1
  fi

  if ! command -v curl >/dev/null 2>&1; then
    printf '\e[31mERROR:\e[0m curl is not installed.\n'
    return 1
  fi

  if ! command -v jq >/dev/null 2>&1; then
    printf '\e[31mERROR:\e[0m jq is not installed.\n'
    return 1
  fi

  printf '\n\e[1;38;5;110m🚀 Welcome to bashGemini\e[0m\n'
  printf '\e[2mPress Ctrl+C to exit\e[0m\n\n'

  while true; do
    read -e -r -p $'\e[32mgemini> \e[0m' prompt

    if [ "$prompt" = "exit" ]; then
      printf '\e[31mGame Over 💀\e[0m\n'
      break
    fi

    if [ "$prompt" = "help" ]; then
      printf '\e[38;5;110mAvailable commands:\e[0m\n'
      printf '\e[38;5;110m  help  - show this help message\e[0m\n'
      printf '\e[38;5;110m  reset - clear conversation history\e[0m\n'
      printf '\e[38;5;110m  exit  - quit bashGemini\e[0m\n\n'
      continue
    fi

    if [ "$prompt" = "reset" ]; then
      : > "$histfile"
      printf '\e[38;5;110mHistory cleared.\e[0m\n\n'
      continue
    fi

    [ -z "$prompt" ] && continue
    history -s "$prompt"

    local full_prompt
    full_prompt=$(
      printf "This is the conversation so far.\n"
      printf "Answer taking into account previous context.\n\n"
      cat "$histfile"
      printf "User: %s\nAssistant:" "$prompt"
    )

    local response
    response=$(
      curl -s -X POST \
        "https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=$GEMINI_API_KEY" \
        -H "Content-Type: application/json" \
        -d "$(jq -n --arg txt "$full_prompt" '{
          contents: [
            {
              parts: [
                { text: $txt }
              ]
            }
          ]
        }')"
    )

    local answer
    answer=$(
      printf '%s' "$response" | jq -r '
        if .candidates and .candidates[0].content.parts then
          .candidates[0].content.parts
          | map(.text // "")
          | join("")
        elif .error then
          "ERROR: \(.error.message)"
        else
          "No response"
        end
      '
    )

    printf '\e[38;5;110m%s\e[0m\n\n' "$answer"

    {
      printf "User: %s\n" "$prompt"
      printf "Assistant: %s\n\n" "$answer"
    } >> "$histfile"
  done

  trap - INT
}
 # ===========================
 gpt() {
############################################################
# bashGPT - Minimal ChatGPT-like CLI using Codex
#
# Features:
# - Minimal interface (no Codex UI, clean output)
# - Conversation memory (context preserved across prompts)
# - Command history (↑ ↓ arrows enabled)
# - Colored prompt (green) and answers (soft blue)
# - Exit message with Ctrl+C or 'exit'
#
# Commands:
# - help  : show available commands
# - reset : clear conversation history
# - exit  : quit bashGPT
#
# Notes:
# - Uses Codex CLI in non-interactive mode (codex exec)
# - Requires Node.js and @openai/codex installed
# - No API key needed if logged in with ChatGPT
############################################################

  local histfile="/tmp/codex_min_history.txt"
  : > "$histfile"

  # Show message on Ctrl+C
  trap 'printf "\n\e[31mGame Over 💀\e[0m\n"; return 130' INT

  # Startup message
  printf '\n\e[1;38;5;110m🚀 Welcome to bashGPT\e[0m\n'
  printf '\e[2mPress Ctrl+C to exit\e[0m\n\n'

  while true; do
    read -e -r -p $'\e[32mgpt> \e[0m' prompt

    if [ "$prompt" = "exit" ]; then
      printf '\e[31mGame Over 💀\e[0m\n'
      break
    fi

    if [ "$prompt" = "help" ]; then
      printf '\e[38;5;110mAvailable commands:\e[0m\n'
      printf '\e[38;5;110m  help  - show this help message\e[0m\n'
      printf '\e[38;5;110m  reset - clear conversation history\e[0m\n'
      printf '\e[38;5;110m  exit  - quit bashGPT\e[0m\n\n'
      continue
    fi

    if [ "$prompt" = "reset" ]; then
      : > "$histfile"
      printf '\e[38;5;110mHistory cleared.\e[0m\n\n'
      continue
    fi

    [ -z "$prompt" ] && continue

    # Save input into bash history
    history -s "$prompt"

    # Build prompt with conversation memory
    local full_prompt
    full_prompt=$(
      printf "This is the conversation so far.\n"
      printf "Answer taking into account previous context.\n\n"
      cat "$histfile"
      printf "User: %s\nAssistant:" "$prompt"
    )

    # Run Codex in non-interactive mode
    local answer
    answer=$(
      NO_COLOR=1 TERM=dumb npx @openai/codex exec \
        --skip-git-repo-check \
        "$full_prompt" 2>/dev/null
    )

    # Print answer in soft blue
    printf '\e[38;5;110m%s\e[0m\n\n' "$answer"

    # Save conversation to local history
    {
      printf "User: %s\n" "$prompt"
      printf "Assistant: %s\n\n" "$answer"
    } >> "$histfile"
  done

  trap - INT
}
#==========================
z() {
  command -v fzf >/dev/null 2>&1 || { echo "fzf non installato"; return 1; }

  local cmd
  cmd="$(history \
    | fzf --tac --reverse --prompt="⌛ Seleziona un comando: " \
    | sed 's/^[ ]*[0-9]\+[ ]*//')"

  if [[ -n "$cmd" ]]; then
    printf '\n  Eseguo: \033[1m%s\033[0m\n' "$cmd"
    eval "$cmd"
  fi
}
# =========================
# acrivate venv 

activate_venv() {
  local venv

  venv="$(find . -maxdepth 2 -name pyvenv.cfg -exec dirname {} \; 2>/dev/null | head -n1)"
  [[ -n "$venv" ]] || return 0

  source "$venv/bin/activate"
}
